spring.datasource.url=jdbc:postgresql://dpg-d8a31knavr4c73d4bl30-a.singapore-postgres.render.com:5432/hospitaldb_m82d
spring.datasource.username=hospitaldb_m82d_user

spring.datasource.password=AIsoUGwcuQk54NSiH0waVVc6S5k3dkIT

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true